name: cicd pipeline

on:
  push:
    branches:
      - dev

jobs:
  JavaPocJob1:
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [11]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout from git
        uses: actions/checkout@v3

      - name: aws creds
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: initialize terraform
        run: terraform init

      - name: terraform planning
        run: terraform plan

      - name: terraform apply changes
        run: terraform apply -auto-approve

      - name: setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}

      - name: build java application
        run: mvn clean install

      # ✅ LOGIN TO DOCKER HUB
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ✅ BUILD & PUSH IMAGE
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

      # ✅ DEPLOY TO EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker run -d --name myapp -p 8081:8081 ${{ secrets.DOCKER_USERNAME }}/myapp:latest